spring.application.name=attachment_agent
# Local Ollama connection

langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3:latest
#GCP
GCP_PROJECT_ID=
GCP_PROCESSOR_ID=
